-- EXPLAIN SELECT first_name 
-- FROM customers
-- WHERE phone REGEXP('^7'); // INDEX NOT WORKING BECAUSE THE PHONE NUMBER IS A STRING (SHOULD USE FULL PREFIX OR FULL TEXT INDEX)

-- CREATE INDEX idx_phone ON customers(phone);
